# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
     - name: Set up nodejs
      - run: npm install
    - name: Install dependencies
      run: |
        python -m pip3 install --upgrade pip3
        python -m pip3 install robotframework-browser
        python -m rfbrowser init
    - name: Test with robot
      run: |
        robot fun.robot
