
name: Browser library fun with robot framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install robotframework-browser
        python -m pip install robotframework-datadriver
        python -m Browser.entry init
        python -m playwright install-deps
    - name: Test with robot
      run: |
        robot first.robot
